resources:
  repositories:
  - repository: treinamento-fullcycle
    type: github
    endpoint: 'treinamento-fullcycle'
    name: MacmillerMartins/treinamento-fullcycle

trigger:
 - main

stages:
- stage: CD
  displayName: CD

  jobs:

  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'sc-dockerhub'
        repository: 'macmiller/argocd-fullcycle'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

  - job: Deploy
    displayName: Deploy
    dependsOn: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:

    - checkout: self
      persistCredentials: true

    - task: KubernetesManifest@0
      displayName: Kustomize
      inputs:
        action: 'bake'
        renderType: 'kustomize'
        kustomizationPath: 'k8s'

    - task: CmdLine@2
      displayName: Update k8s
      inputs:
        script: |
          cd k8s
          kustomize edit set image goapp=macmiller/argocd-fullcycle:$(Build.BuildId)
          cat kustomization.yaml

    - task: CmdLine@2
      displayName: Git Config
      inputs:
        script: |
          git config --local user.email "macmiller_ferreira@hotmail.com"
          git config --local user.name "MacmillerMartins"

    - task: CmdLine@2
      displayName: Git Checkout
      inputs:
        script: |
          git checkout -b $(Build.SourceBranchName)

    - task: CmdLine@2
      displayName: Git Add and Commit
      inputs:
        script: |
          git add .
          git commit -m "change image tag"

    - task: CmdLine@2
      displayName: Git Push
      inputs:
        script: |
          git push --set-upstream origin $(Build.SourceBranchName)
