apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: goapp
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080